# Generated by Django 4.2.30 on 2026-06-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='applied_at',
            field=models.DateField(blank=True, null=True, verbose_name='申請日'),
        ),
        migrations.AddField(
            model_name='case',
            name='completed_at',
            field=models.DateField(blank=True, null=True, verbose_name='完了日'),
        ),
        migrations.AddField(
            model_name='case',
            name='result_notified_at',
            field=models.DateField(blank=True, null=True, verbose_name='結果通知日'),
        ),
    ]
