# Generated by Django 4.2.30 on 2026-07-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_casechecklisttemplate_casechecklisttemplateitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casechecklisttemplate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casechecklisttemplateitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casechecklisttemplateitem',
            name='deleted_with_template',
            field=models.BooleanField(default=False),
        ),
    ]
