# Generated by Django 4.2.30 on 2026-07-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_casechecklisttemplate_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
