# Generated by Django 4.2.30 on 2026-07-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_alter_case_case_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='casechecklistitem',
            name='acquisition_place',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='casechecklistitem',
            name='customer_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='casechecklistitem',
            name='importance_level',
            field=models.CharField(choices=[('normal', '通常'), ('important', '重要'), ('warning', '要注意')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='casechecklistitem',
            name='internal_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='casechecklistitem',
            name='is_visible_to_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='casechecklistitem',
            name='required_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='casechecklistitem',
            name='responsible_party',
            field=models.CharField(blank=True, choices=[('customer', '顧客本人'), ('company', '会社'), ('our_company', '本公司代办'), ('gyousei', '行政書士'), ('tax_accountant', '税理士'), ('other', 'その他')], max_length=30),
        ),
        migrations.AddField(
            model_name='casechecklisttemplateitem',
            name='acquisition_place',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='casechecklisttemplateitem',
            name='customer_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='casechecklisttemplateitem',
            name='importance_level',
            field=models.CharField(choices=[('normal', '通常'), ('important', '重要'), ('warning', '要注意')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='casechecklisttemplateitem',
            name='internal_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='casechecklisttemplateitem',
            name='is_visible_to_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='casechecklisttemplateitem',
            name='required_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='casechecklisttemplateitem',
            name='responsible_party',
            field=models.CharField(blank=True, choices=[('customer', '顧客本人'), ('company', '会社'), ('our_company', '本公司代办'), ('gyousei', '行政書士'), ('tax_accountant', '税理士'), ('other', 'その他')], max_length=30),
        ),
    ]
