# Generated by Django 4.2.30 on 2026-07-16 02:18

from django.db import migrations, models


def migrate_case_statuses(apps, schema_editor):
    Case = apps.get_model('cases', 'Case')
    status_mapping = {
        'open': 'accepted',
        '受付': 'accepted',
        '受付中': 'accepted',
        'in_progress': 'collecting_documents',
        '進行中': 'collecting_documents',
        '準備中': 'collecting_documents',
        '受任中': 'accepted',
        '申請中': 'applied',
        '結果通知済': 'approved',
        '補正対応中': 'additional_documents',
        'completed': 'completed',
        '完了': 'completed',
        'closed': 'completed',
        '終了': 'completed',
        '中止': 'withdrawn',
    }
    inactive_values = {'中止'}
    archived_values = {'closed', '終了'}
    for case in Case.objects.all().only('id', 'status', 'registration_status'):
        old_status = case.status
        case.status = status_mapping.get(old_status, 'accepted')
        if old_status in inactive_values:
            case.registration_status = 'inactive'
        elif old_status in archived_values:
            case.registration_status = 'archived'
        else:
            case.registration_status = 'active'
        case.save(update_fields=['status', 'registration_status'])


def reverse_case_statuses(apps, schema_editor):
    Case = apps.get_model('cases', 'Case')
    reverse_mapping = {
        'consultation': 'open',
        'accepted': 'open',
        'collecting_documents': 'in_progress',
        'preparing_documents': 'in_progress',
        'ready_to_apply': 'in_progress',
        'applied': 'in_progress',
        'under_review': 'in_progress',
        'additional_documents': 'in_progress',
        'approved': 'completed',
        'rejected': 'completed',
        'withdrawn': 'closed',
        'completed': 'completed',
    }
    for case in Case.objects.all().only('id', 'status'):
        case.status = reverse_mapping.get(case.status, 'open')
        case.save(update_fields=['status'])


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_casechecklistitem_acquisition_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='registration_status',
            field=models.CharField(choices=[('active', '有効'), ('inactive', '無効'), ('archived', 'アーカイブ')], default='active', max_length=20),
        ),
        migrations.RunPython(migrate_case_statuses, reverse_case_statuses),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('consultation', '相談中'), ('accepted', '受任済み'), ('collecting_documents', '資料準備中'), ('preparing_documents', '書類作成中'), ('ready_to_apply', '申請準備完了'), ('applied', '申請済み'), ('under_review', '審査中'), ('additional_documents', '追加資料対応中'), ('approved', '許可'), ('rejected', '不許可'), ('withdrawn', '取下げ'), ('completed', '完了')], default='accepted', max_length=20),
        ),
    ]
