# Generated by Django 4.2.30 on 2026-07-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_case_registration_status_alter_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='additional_documents_detail',
            field=models.TextField(blank=True, verbose_name='追加資料内容'),
        ),
        migrations.AddField(
            model_name='case',
            name='additional_documents_due_at',
            field=models.DateField(blank=True, null=True, verbose_name='追加資料期限'),
        ),
        migrations.AddField(
            model_name='case',
            name='additional_documents_requested_at',
            field=models.DateField(blank=True, null=True, verbose_name='追加資料依頼日'),
        ),
        migrations.AddField(
            model_name='case',
            name='additional_documents_submitted_at',
            field=models.DateField(blank=True, null=True, verbose_name='追加資料提出日'),
        ),
        migrations.AddField(
            model_name='case',
            name='application_authority',
            field=models.CharField(blank=True, max_length=150, verbose_name='申請先'),
        ),
        migrations.AddField(
            model_name='case',
            name='application_ready_at',
            field=models.DateField(blank=True, null=True, verbose_name='申請準備完了日'),
        ),
        migrations.AddField(
            model_name='case',
            name='application_receipt_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='受付番号'),
        ),
        migrations.AddField(
            model_name='case',
            name='archived_at',
            field=models.DateField(blank=True, null=True, verbose_name='アーカイブ日'),
        ),
        migrations.AddField(
            model_name='case',
            name='consulted_at',
            field=models.DateField(blank=True, null=True, verbose_name='相談日'),
        ),
        migrations.AddField(
            model_name='case',
            name='document_collection_started_at',
            field=models.DateField(blank=True, null=True, verbose_name='資料待ち開始日'),
        ),
        migrations.AddField(
            model_name='case',
            name='documents_completed_at',
            field=models.DateField(blank=True, null=True, verbose_name='必要資料完了日'),
        ),
        migrations.AddField(
            model_name='case',
            name='expected_result_at',
            field=models.DateField(blank=True, null=True, verbose_name='結果予定日'),
        ),
        migrations.AddField(
            model_name='case',
            name='next_action',
            field=models.TextField(blank=True, verbose_name='次の対応'),
        ),
        migrations.AddField(
            model_name='case',
            name='next_action_due_at',
            field=models.DateField(blank=True, null=True, verbose_name='対応期限'),
        ),
        migrations.AddField(
            model_name='case',
            name='result_note',
            field=models.TextField(blank=True, verbose_name='結果備考'),
        ),
        migrations.AddField(
            model_name='case',
            name='result_received_at',
            field=models.DateField(blank=True, null=True, verbose_name='結果受領日'),
        ),
        migrations.AddField(
            model_name='case',
            name='review_started_at',
            field=models.DateField(blank=True, null=True, verbose_name='審査開始日'),
        ),
        migrations.AddField(
            model_name='case',
            name='status_changed_at',
            field=models.DateField(blank=True, null=True, verbose_name='進捗変更日'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('consultation', '相談中'), ('accepted', '受任済み'), ('collecting_documents', '資料待ち'), ('preparing_documents', '書類作成中'), ('ready_to_apply', '申請準備完了'), ('applied', '申請済み'), ('under_review', '審査中'), ('additional_documents', '追加資料対応中'), ('approved', '許可'), ('rejected', '不許可'), ('withdrawn', '取下げ'), ('completed', '完了')], default='accepted', max_length=20),
        ),
    ]
