# Generated by Django 4.2.30 on 2026-07-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_case_additional_documents_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='permission_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='許可番号'),
        ),
        migrations.AddField(
            model_name='case',
            name='withdrawn_at',
            field=models.DateField(blank=True, null=True, verbose_name='取下げ日'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('consultation', '相談中'), ('accepted', '受任済み'), ('collecting_documents', '資料準備中'), ('preparing_documents', '書類作成中'), ('ready_to_apply', '申請準備完了'), ('applied', '申請済み'), ('under_review', '審査中'), ('additional_documents', '追加資料対応中'), ('additional_documents_submitted', '追加資料提出済み'), ('approved', '許可'), ('rejected', '不許可'), ('withdrawn', '取下げ'), ('completed', '完了')], default='accepted', max_length=30),
        ),
    ]
