# Generated by Django 4.2.30 on 2026-07-16 10:39

from django.db import migrations, models
import django.db.models.deletion


CASE_TYPES = [
    ('経営・管理', 'business_manager', '経管', 10),
    ('技術・人文知識・国際業務', 'engineer_humanities', '技人国', 20),
    ('高度専門職', 'highly_skilled', '高度', 30),
    ('永住許可', 'permanent_residence', '永住', 40),
    ('家族滞在', 'dependent', '家族', 50),
    ('特定活動', 'designated_activities', '特定', 60),
    ('その他', 'other', 'その他', 999),
]

APPLICATION_CATEGORIES = [
    ('新規', 'new', '新規', 10),
    ('更新', 'renewal', '更新', 20),
    ('変更', 'change', '変更', 30),
    ('認定', 'certificate', '認定', 40),
    ('取得', 'acquisition', '取得', 50),
    ('その他', 'other', 'その他', 999),
]

STATUS_SETTINGS = [
    ('consultation', '相談中', 10, False),
    ('accepted', '受任済み', 20, False),
    ('collecting_documents', '資料準備中', 30, True),
    ('preparing_documents', '書類作成中', 40, True),
    ('ready_to_apply', '申請準備完了', 50, True),
    ('applied', '申請済み', 60, True),
    ('under_review', '審査中', 70, True),
    ('additional_documents', '追加資料対応中', 80, True),
    ('additional_documents_submitted', '追加資料提出済み', 90, True),
    ('approved', '許可', 100, True),
    ('rejected', '不許可', 110, True),
    ('withdrawn', '取下げ', 120, True),
    ('completed', '完了', 130, True),
]

ACQUISITION_PLACES = [
    ('本人準備', 10),
    ('会社準備', 20),
    ('大阪南税務署', 30),
    ('大阪市税事務所', 40),
    ('年金事務所', 50),
    ('ハローワーク', 60),
    ('法務局', 70),
    ('市区町村役所', 80),
    ('その他', 999),
]

RESPONSIBLE_PARTIES = [
    ('顧客本人', 'customer', 10),
    ('顧客会社', 'company', 20),
    ('弊社', 'our_company', 30),
    ('行政書士', 'gyousei', 40),
    ('税理士', 'tax_accountant', 50),
    ('その他', 'other', 999),
]


def infer_case_type_code(case_type):
    text = case_type or ''
    if '経営' in text or '経管' in text:
        return 'business_manager'
    if '技人国' in text or '技術・人文知識・国際業務' in text:
        return 'engineer_humanities'
    if '高度' in text:
        return 'highly_skilled'
    if '永住' in text:
        return 'permanent_residence'
    if '家族' in text:
        return 'dependent'
    if '特定' in text:
        return 'designated_activities'
    return 'other'


def infer_application_category_code(case_type):
    text = case_type or ''
    if '更新' in text:
        return 'renewal'
    if '変更' in text:
        return 'change'
    if '認定' in text:
        return 'certificate'
    if '取得' in text:
        return 'acquisition'
    if '新規' in text or '申請' in text:
        return 'new'
    return 'other'


def seed_case_settings(apps, schema_editor):
    CaseTypeMaster = apps.get_model('cases', 'CaseTypeMaster')
    CaseApplicationCategory = apps.get_model('cases', 'CaseApplicationCategory')
    CaseStatusSetting = apps.get_model('cases', 'CaseStatusSetting')
    AcquisitionPlacePreset = apps.get_model('cases', 'AcquisitionPlacePreset')
    ResponsiblePartyPreset = apps.get_model('cases', 'ResponsiblePartyPreset')
    Case = apps.get_model('cases', 'Case')

    case_type_by_code = {}
    for name, code, abbreviation, sort_order in CASE_TYPES:
        obj, _ = CaseTypeMaster.objects.update_or_create(
            code=code,
            defaults={
                'name': name,
                'number_abbreviation': abbreviation,
                'sort_order': sort_order,
                'is_active': True,
            },
        )
        case_type_by_code[code] = obj

    application_by_code = {}
    for name, code, abbreviation, sort_order in APPLICATION_CATEGORIES:
        obj, _ = CaseApplicationCategory.objects.update_or_create(
            code=code,
            defaults={
                'name': name,
                'number_abbreviation': abbreviation,
                'sort_order': sort_order,
                'is_active': True,
            },
        )
        application_by_code[code] = obj

    for code, display_name, sort_order, is_visible in STATUS_SETTINGS:
        CaseStatusSetting.objects.update_or_create(
            code=code,
            defaults={
                'display_name': display_name,
                'sort_order': sort_order,
                'is_visible': is_visible,
            },
        )

    for name, sort_order in ACQUISITION_PLACES:
        AcquisitionPlacePreset.objects.update_or_create(
            name=name,
            defaults={'sort_order': sort_order, 'is_active': True},
        )

    for name, code, sort_order in RESPONSIBLE_PARTIES:
        ResponsiblePartyPreset.objects.update_or_create(
            code=code,
            defaults={'name': name, 'sort_order': sort_order, 'is_active': True},
        )

    for case in Case.objects.filter(case_type_master__isnull=True):
        case_type = case_type_by_code[infer_case_type_code(case.case_type)]
        application_category = application_by_code[infer_application_category_code(case.case_type)]
        Case.objects.filter(pk=case.pk).update(
            case_type_master=case_type,
            application_category=application_category,
        )


def unseed_case_settings(apps, schema_editor):
    # Do not delete seeded master rows on reverse; historical cases may reference them.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_case_permission_number_case_withdrawn_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionPlacePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'case_acquisition_place_presets',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CaseApplicationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('number_abbreviation', models.CharField(blank=True, max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'case_application_categories',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CaseStatusSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('display_name', models.CharField(max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'case_status_settings',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CaseTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('number_abbreviation', models.CharField(blank=True, max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'case_type_masters',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResponsiblePartyPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'case_responsible_party_presets',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='application_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.caseapplicationcategory'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_type_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.casetypemaster'),
        ),
        migrations.RunPython(seed_case_settings, unseed_case_settings),
    ]
