# Generated by Django 4.2.30 on 2026-08-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_acquisitionplacepreset_caseapplicationcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItemPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('acquisition_place', models.CharField(blank=True, max_length=255)),
                ('responsible_party', models.CharField(blank=True, choices=[('customer', '顧客本人'), ('company', '会社'), ('our_company', '本公司代办'), ('gyousei', '行政書士'), ('tax_accountant', '税理士'), ('other', 'その他')], max_length=30)),
                ('required_details', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'case_checklist_item_presets',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
