# Generated by Django 4.2.30 on 2026-08-08 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_checklistitempreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='casechecklisttemplate',
            name='application_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_templates', to='cases.caseapplicationcategory'),
        ),
        migrations.AddField(
            model_name='casechecklisttemplate',
            name='case_type_master',
            field=models.ForeignKey(blank=True, help_text='この案件種別・申請区分の組み合わせで案件を作成した際、自動的にこのテンプレートを適用する。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_templates', to='cases.casetypemaster'),
        ),
    ]
