# Generated by Django 4.2.30 on 2026-08-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_seed_engineer_humanities_change_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='residence_card_received_at',
            field=models.DateField(blank=True, null=True, verbose_name='在留カード受取日'),
        ),
    ]
