# Generated by Django 4.2.30 on 2026-09-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_apply_change_template_to_case_zhang_jing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-created_at'], 'permissions': [('use_cases', '案件業務の利用'), ('case_view_all', '担当外を含む全案件の閲覧'), ('case_change_all', '担当外・未割当を含む全案件の変更'), ('manage_case_settings', '案件種別・テンプレート・担当者などの設定管理')]},
        ),
    ]
