# Generated by Django 4.2.30 on 2026-09-28 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0017_alter_case_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='next_action_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_next_actions', to='employees.employee', verbose_name='次の対応の担当者'),
        ),
        migrations.AddField(
            model_name='case',
            name='next_action_blocked_reason',
            field=models.TextField(blank=True, verbose_name='次の対応の阻害要因'),
        ),
        migrations.AddField(
            model_name='case',
            name='next_action_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='次の対応の完了日時'),
        ),
        migrations.AddField(
            model_name='case',
            name='next_action_completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_case_next_actions', to=settings.AUTH_USER_MODEL, verbose_name='次の対応の完了者'),
        ),
        migrations.AddField(
            model_name='case',
            name='waiting_note',
            field=models.TextField(blank=True, verbose_name='待機メモ'),
        ),
        migrations.AddField(
            model_name='case',
            name='waiting_reason',
            field=models.CharField(blank=True, choices=[('customer_documents', '顧客資料待ち'), ('immigration_review', '入管審査待ち'), ('third_party', '関係先回答待ち'), ('payment', '入金待ち'), ('other', 'その他')], max_length=30, verbose_name='待機理由'),
        ),
        migrations.AddField(
            model_name='case',
            name='waiting_since',
            field=models.DateField(blank=True, null=True, verbose_name='待機開始日'),
        ),
        migrations.AddField(
            model_name='case',
            name='waiting_until',
            field=models.DateField(blank=True, null=True, verbose_name='待機予定終了日'),
        ),
        migrations.AddField(
            model_name='case',
            name='work_status',
            field=models.CharField(choices=[('active', '対応中'), ('waiting', '待機中')], default='active', max_length=20, verbose_name='作業状態'),
        ),
    ]
