# Generated by Django 4.2.30 on 2026-09-28 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_options'),
        ('cases', '0018_case_work_status_next_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='casechecklistitem',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_items', to='documents.document', verbose_name='関連ファイル'),
        ),
        migrations.AddField(
            model_name='casechecklistitem',
            name='received_at',
            field=models.DateField(blank=True, null=True, verbose_name='受領日'),
        ),
    ]
