# Generated by Django 4.2.30 on 2026-09-29 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0019_checklist_item_document_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='archive_reason',
            field=models.CharField(blank=True, max_length=500, verbose_name='アーカイブ理由'),
        ),
        migrations.AddField(
            model_name='case',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='アーカイブ実行者'),
        ),
        migrations.AddField(
            model_name='case',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最終復元日時'),
        ),
        migrations.AddField(
            model_name='case',
            name='restored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最終復元者'),
        ),
    ]
