# Generated by Django 4.2.30 on 2026-10-06 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_db_defaults_for_rollback_compat'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='コード')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('family', models.CharField(choices=[('immigration', '入管申請'), ('professional', '専門家委託'), ('employee_procedure', '従業員・社会保険手続'), ('general', '汎用')], max_length=30, verbose_name='フローの系統')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='並び順')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'case_workflow_templates',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='parent_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_cases', to='cases.case', verbose_name='関連元の案件'),
        ),
        migrations.AddField(
            model_name='case',
            name='service_items',
            field=models.JSONField(blank=True, default=list, verbose_name='サービス項目（参考）'),
        ),
        migrations.AddField(
            model_name='casetypemaster',
            name='requires_application_category',
            field=models.BooleanField(default=True, verbose_name='申請区分が必要'),
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, verbose_name='コード')),
                ('name', models.CharField(max_length=80, verbose_name='段階名')),
                ('base_status', models.CharField(choices=[('consultation', '相談中'), ('accepted', '受任済み'), ('collecting_documents', '資料準備中'), ('preparing_documents', '書類作成中'), ('ready_to_apply', '申請準備完了'), ('applied', '申請済み'), ('under_review', '審査中'), ('additional_documents', '追加資料対応中'), ('additional_documents_submitted', '追加資料提出済み'), ('approved', '許可'), ('rejected', '不許可'), ('withdrawn', '取下げ'), ('completed', '完了')], max_length=30, verbose_name='対応する進捗')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='並び順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='cases.workflowtemplate', verbose_name='業務フロー')),
            ],
            options={
                'db_table': 'case_workflow_stages',
                'ordering': ['template_id', 'sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='workflow_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.workflowstage', verbose_name='現在の段階'),
        ),
        migrations.AddField(
            model_name='case',
            name='workflow_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.workflowtemplate', verbose_name='業務フロー'),
        ),
        migrations.AddField(
            model_name='casetypemaster',
            name='workflow_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_types', to='cases.workflowtemplate', verbose_name='業務フロー'),
        ),
        migrations.AddConstraint(
            model_name='workflowstage',
            constraint=models.UniqueConstraint(fields=('template', 'code'), name='uniq_workflow_stage_code'),
        ),
    ]
