# Generated by Django 4.2.30 on 2026-08-30 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DismissedDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('customer', '顧客'), ('family_member', '家族（旧仕様）'), ('company', '会社')], max_length=20)),
                ('source_id', models.PositiveIntegerField()),
                ('deadline_type', models.CharField(choices=[('residence_expiry', '在留期限'), ('passport_expiry', 'パスポート期限'), ('fiscal_declaration', '決算申告期限')], max_length=30)),
                ('deadline_date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dismissed_deadlines',
                'unique_together': {('source_type', 'source_id', 'deadline_type', 'deadline_date')},
            },
        ),
    ]
