# Generated by Django 4.2.30 on 2026-07-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField(verbose_name='日付')),
                ('place', models.CharField(blank=True, max_length=255, verbose_name='場所')),
                ('category', models.CharField(max_length=50, verbose_name='カテゴリ')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='金額')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='支払方法')),
                ('expense_target', models.CharField(blank=True, max_length=150, verbose_name='費用対象')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('is_reimbursed', models.BooleanField(default=False, verbose_name='精算済み')),
                ('is_exported', models.BooleanField(default=False, verbose_name='出力済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '支出記録',
                'verbose_name_plural': '支出記録',
                'db_table': 'accounting_expenses',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='カテゴリ名')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='並び順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '支出カテゴリ',
                'verbose_name_plural': '支出カテゴリ',
                'db_table': 'accounting_expense_categories',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_date', models.DateField(verbose_name='日付')),
                ('source_target', models.CharField(blank=True, max_length=150, verbose_name='対象')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='金額')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('is_exported', models.BooleanField(default=False, verbose_name='出力済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '収入来源',
                'verbose_name_plural': '収入来源',
                'db_table': 'accounting_income_sources',
                'ordering': ['-source_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField(verbose_name='日付')),
                ('place', models.CharField(blank=True, max_length=255, verbose_name='場所')),
                ('distance_km', models.DecimalField(decimal_places=1, max_digits=8, verbose_name='走行距離')),
                ('usage_target', models.CharField(blank=True, max_length=150, verbose_name='利用対象')),
                ('purpose', models.CharField(blank=True, max_length=100, verbose_name='用途')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('is_exported', models.BooleanField(default=False, verbose_name='出力済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '用車記録',
                'verbose_name_plural': '用車記録',
                'db_table': 'accounting_vehicle_usages',
                'ordering': ['-usage_date', '-created_at'],
            },
        ),
    ]
