# Generated by Django 4.2.30 on 2026-07-03 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_seed_expense_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目说明')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目收支表',
                'verbose_name_plural': '项目收支表',
                'db_table': 'accounting_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountingProjectIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_date', models.DateField(verbose_name='收入日期')),
                ('income_target', models.CharField(blank=True, max_length=255, verbose_name='收入对象')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_incomes', to='accounting.accountingproject', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目收入',
                'verbose_name_plural': '项目收入',
                'db_table': 'accounting_project_incomes',
                'ordering': ['-income_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AccountingProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField(verbose_name='支出日期')),
                ('place', models.CharField(blank=True, max_length=255, verbose_name='地点')),
                ('category_name', models.CharField(blank=True, max_length=255, verbose_name='类别')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额')),
                ('payment_method', models.CharField(blank=True, max_length=100, verbose_name='支付方式')),
                ('expense_target', models.CharField(blank=True, max_length=255, verbose_name='费用对象')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_expenses', to='accounting.accountingproject', verbose_name='项目')),
                ('source_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_copies', to='accounting.expense', verbose_name='来源支出记录')),
            ],
            options={
                'verbose_name': '项目支出',
                'verbose_name_plural': '项目支出',
                'db_table': 'accounting_project_expenses',
                'ordering': ['-expense_date', '-id'],
            },
        ),
    ]
