# Generated by Django 4.2.30 on 2026-07-03 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0003_accountingproject_accountingprojectincome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('invoice', '請求書'), ('receipt', '領収書')], max_length=20, verbose_name='帳票種別')),
                ('voucher_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='帳票番号')),
                ('issue_date', models.DateField(verbose_name='発行日')),
                ('recipient_name', models.CharField(blank=True, max_length=255, verbose_name='宛先会社名')),
                ('recipient_postal_code', models.CharField(blank=True, max_length=20, verbose_name='宛先郵便番号')),
                ('recipient_address', models.TextField(blank=True, verbose_name='宛先住所')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='件名 / 但し書き')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='金額')),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='消費税額')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='合計金額')),
                ('details', models.TextField(blank=True, verbose_name='明細')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('payment_due_date', models.DateField(blank=True, null=True, verbose_name='支払期限')),
                ('payment_method', models.CharField(blank=True, max_length=100, verbose_name='支払方法')),
                ('issuer_name', models.CharField(default='SUNRISE日晟鴻達株式会社', max_length=255, verbose_name='発行者名')),
                ('issuer_postal_code', models.CharField(blank=True, max_length=20, verbose_name='発行者郵便番号')),
                ('issuer_address', models.TextField(blank=True, verbose_name='発行者住所')),
                ('issuer_tel', models.CharField(blank=True, max_length=50, verbose_name='発行者電話番号')),
                ('issuer_registration_number', models.CharField(blank=True, max_length=100, verbose_name='登録番号')),
                ('bank_info', models.TextField(blank=True, verbose_name='振込先')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '帳票',
                'verbose_name_plural': '帳票',
                'db_table': 'accounting_vouchers',
                'ordering': ['-issue_date', '-id'],
            },
        ),
    ]
