# Generated by Django 4.2.30 on 2026-07-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_accountingvoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingvoucher',
            name='line_items',
            field=models.JSONField(blank=True, default=list, verbose_name='明細行'),
        ),
    ]
