# Generated by Django 4.2.30 on 2026-07-03

from django.db import migrations, models


DEFAULT_ITEMS = [
    '在留資格更新申請サポート費用',
    '在留資格変更申請サポート費用',
    '経営管理ビザ申請サポート費用',
    '永住申請サポート費用',
    '書類作成費用',
    '翻訳費用',
    '相談料',
    '役所同行費',
    '入管同行費',
    '交通費',
    '郵送費',
    'サーバー費用',
    'ホームページ制作費用',
    'その他',
]


def seed_default_items(apps, schema_editor):
    VoucherItemTemplate = apps.get_model('accounting', 'VoucherItemTemplate')
    for index, name in enumerate(DEFAULT_ITEMS, start=1):
        VoucherItemTemplate.objects.get_or_create(
            name=name,
            defaults={
                'sort_order': index,
                'is_active': True,
            },
        )


def remove_default_items(apps, schema_editor):
    VoucherItemTemplate = apps.get_model('accounting', 'VoucherItemTemplate')
    VoucherItemTemplate.objects.filter(name__in=DEFAULT_ITEMS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_accountingvoucher_line_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='項目名')),
                ('default_unit_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='默认单价')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='並び順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '帳票明細項目',
                'verbose_name_plural': '帳票明細項目',
                'db_table': 'accounting_voucher_item_templates',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RunPython(seed_default_items, remove_default_items),
    ]
