# Generated by Django 4.2.30 on 2026-07-04 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0006_voucheritemtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaReturnApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(blank=True, max_length=255, verbose_name='申请人姓名')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='国籍')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('gender', models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性')], max_length=20, verbose_name='性別')),
                ('marital_status', models.CharField(blank=True, choices=[('single', '未婚'), ('married', '既婚'), ('divorced', '離婚'), ('widowed', '死別')], max_length=20, verbose_name='婚姻状況')),
                ('passport_number', models.CharField(blank=True, max_length=100, verbose_name='旅券番号')),
                ('passport_issue_date', models.DateField(blank=True, null=True, verbose_name='旅券発行日')),
                ('passport_expiry_date', models.DateField(blank=True, null=True, verbose_name='旅券期限')),
                ('residence_status', models.CharField(blank=True, max_length=100, verbose_name='在留資格')),
                ('address', models.TextField(blank=True, verbose_name='住所')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='メール')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='職業')),
                ('guarantor_name', models.CharField(blank=True, max_length=255, verbose_name='保証人氏名')),
                ('guarantor_phone', models.CharField(blank=True, max_length=50, verbose_name='保証人電話番号')),
                ('guarantor_address', models.TextField(blank=True, verbose_name='保証人住所')),
                ('guarantor_relationship', models.CharField(blank=True, max_length=100, verbose_name='申請人との関係')),
                ('guarantor_occupation', models.CharField(blank=True, max_length=100, verbose_name='保証人職業')),
                ('guarantor_snapshot', models.JSONField(blank=True, default=dict, verbose_name='保証人スナップショット')),
                ('form_data', models.JSONField(blank=True, default=dict, verbose_name='表单数据')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visa_return_applications', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '返签visa表',
                'verbose_name_plural': '返签visa表',
                'db_table': 'accounting_visa_return_applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
