# Generated by Django 4.2.30 on 2026-07-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_visareturnapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaGuarantorTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='模板名称')),
                ('guarantor_name', models.CharField(blank=True, max_length=255, verbose_name='在日担保人姓名')),
                ('guarantor_name_en', models.CharField(blank=True, max_length=255, verbose_name='在日担保人英文姓名')),
                ('guarantor_phone', models.CharField(blank=True, max_length=50, verbose_name='电话')),
                ('guarantor_address', models.TextField(blank=True, verbose_name='日文地址')),
                ('guarantor_address_en', models.TextField(blank=True, verbose_name='英文地址')),
                ('guarantor_birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('guarantor_nationality', models.CharField(blank=True, max_length=100, verbose_name='国籍')),
                ('guarantor_visa_status', models.CharField(blank=True, max_length=100, verbose_name='签证种类 / 在留资格')),
                ('guarantor_occupation', models.CharField(blank=True, max_length=100, verbose_name='职业 / 职务')),
                ('guarantor_relationship', models.CharField(blank=True, max_length=100, verbose_name='与申请人的关系')),
                ('guarantor_company_name', models.CharField(blank=True, max_length=255, verbose_name='公司名')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '在日担保人模板',
                'verbose_name_plural': '在日担保人模板',
                'db_table': 'accounting_visa_guarantor_templates',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
