# Generated by Django 4.2.30 on 2026-07-10 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0008_visaguarantortemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeifuNoticePdfRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='记录名称')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('completed', '完了')], default='draft', max_length=20, verbose_name='状态')),
                ('text_items', models.JSONField(blank=True, default=list, verbose_name='追加文字')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seifu_notice_pdf_records', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '清風合格通知書记录',
                'verbose_name_plural': '清風合格通知書记录',
                'db_table': 'accounting_seifu_notice_pdf_records',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
