# Generated by Django 4.2.30 on 2026-07-11 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('companies', '0005_company_representative_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0004_customer_my_number_customer_postal_code_and_more'),
        ('accounting', '0009_seifunoticepdfrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRenewalVoucherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='记录名称')),
                ('category', models.CharField(choices=[('renewal', '更新用'), ('pension', '年金加入')], default='renewal', max_length=20, verbose_name='分类')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('completed', '完了')], default='draft', max_length=20, verbose_name='状态')),
                ('has_employees', models.BooleanField(default=False, verbose_name='是否有雇员')),
                ('has_dependents', models.BooleanField(default=False, verbose_name='是否有抚养人')),
                ('selected_templates', models.JSONField(blank=True, default=list, verbose_name='选择模板')),
                ('form_data', models.JSONField(blank=True, default=dict, verbose_name='表单数据')),
                ('generated_files', models.JSONField(blank=True, default=list, verbose_name='生成文件')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_renewal_voucher_records', to='companies.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_renewal_voucher_records', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_renewal_voucher_records', to='customers.customer', verbose_name='顧客')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_renewal_voucher_records', to='employees.employee', verbose_name='担当者')),
            ],
            options={
                'verbose_name': '税务证明更新用记录',
                'verbose_name_plural': '税务证明更新用记录',
                'db_table': 'accounting_tax_renewal_voucher_records',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
