# Generated by Django 4.2.30 on 2026-07-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_taxrenewalvoucherrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRenewalAgentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='模板名称')),
                ('agent_name', models.CharField(max_length=255, verbose_name='代理人姓名')),
                ('agent_kana', models.CharField(blank=True, max_length=255, verbose_name='代理人假名')),
                ('agent_address', models.TextField(blank=True, verbose_name='代理人地址')),
                ('agent_phone', models.CharField(blank=True, max_length=50, verbose_name='代理人电话')),
                ('agent_company_name', models.CharField(blank=True, max_length=255, verbose_name='代理公司名')),
                ('agent_position', models.CharField(blank=True, max_length=100, verbose_name='职务')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '税务证明代理人模板',
                'verbose_name_plural': '税务证明代理人模板',
                'db_table': 'accounting_tax_renewal_agent_templates',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
