# Generated by Django 4.2.30 on 2026-08-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_voucher_line_item_tax_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingvoucher',
            name='recipient_honorific',
            field=models.CharField(blank=True, choices=[('御中', '御中'), ('様', '様'), ('', 'なし')], default='御中', max_length=10, verbose_name='敬称'),
        ),
    ]
