# Generated by Django 4.2.30 on 2026-08-08 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_casechecklisttemplate_application_category_and_more'),
        ('accounting', '0013_accountingvoucher_recipient_honorific'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrenewalvoucherrecord',
            name='case',
            field=models.ForeignKey(blank=True, help_text='選択すると、その案件の顧客・会社・担当者を自動的に反映できる。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_renewal_voucher_records', to='cases.case', verbose_name='案件'),
        ),
    ]
