# Generated by Django 4.2.30 on 2026-09-27 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0014_taxrenewalvoucherrecord_case'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingproject',
            options={'ordering': ['-created_at'], 'permissions': [('use_project', 'プロジェクト収支の利用')], 'verbose_name': '项目收支表', 'verbose_name_plural': '项目收支表'},
        ),
        migrations.AlterModelOptions(
            name='accountingvoucher',
            options={'ordering': ['-issue_date', '-id'], 'permissions': [('use_voucher', '請求書・領収書の利用')], 'verbose_name': '帳票', 'verbose_name_plural': '帳票'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date', '-created_at'], 'permissions': [('use_expense', '支出記録（本人分）の利用'), ('expense_view_all', '他人の支出記録の閲覧（読み取り専用）'), ('expense_change_all', '他人の支出記録の変更・削除'), ('expense_export_all', '他人の支出記録を含むExcel出力')], 'verbose_name': '支出記録', 'verbose_name_plural': '支出記録'},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['sort_order', 'id'], 'permissions': [('manage_expense_category', '支出カテゴリの登録・変更（業務権限）')], 'verbose_name': '支出カテゴリ', 'verbose_name_plural': '支出カテゴリ'},
        ),
        migrations.AlterModelOptions(
            name='incomesource',
            options={'ordering': ['-source_date', '-created_at'], 'permissions': [('use_income', '収入元の利用')], 'verbose_name': '収入来源', 'verbose_name_plural': '収入来源'},
        ),
        migrations.AlterModelOptions(
            name='seifunoticepdfrecord',
            options={'ordering': ['-updated_at', '-id'], 'permissions': [('use_seifu', '清風合格通知書の利用')], 'verbose_name': '清風合格通知書记录', 'verbose_name_plural': '清風合格通知書记录'},
        ),
        migrations.AlterModelOptions(
            name='taxrenewalvoucherrecord',
            options={'ordering': ['-updated_at', '-id'], 'permissions': [('use_tax_renewal', '税務証明更新用の利用')], 'verbose_name': '税务证明更新用记录', 'verbose_name_plural': '税务证明更新用记录'},
        ),
        migrations.AlterModelOptions(
            name='vehicleusage',
            options={'ordering': ['-usage_date', '-created_at'], 'permissions': [('use_vehicle', '車両使用記録の利用')], 'verbose_name': '用車記録', 'verbose_name_plural': '用車記録'},
        ),
        migrations.AlterModelOptions(
            name='visareturnapplication',
            options={'ordering': ['-created_at'], 'permissions': [('use_visa', '返签visa表の利用')], 'verbose_name': '返签visa表', 'verbose_name_plural': '返签visa表'},
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='expense',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_expenses', to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_expenses', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者'),
        ),
    ]
