# Generated by Django 4.2.30 on 2026-09-28 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_party_link_permissions'),
        ('cases', '0019_checklist_item_document_link'),
        ('companies', '0010_company_representative_address_and_more'),
        ('accounting', '0015_expense_owner_and_business_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_links', to='cases.case', verbose_name='関連案件'),
        ),
        migrations.AddField(
            model_name='expense',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_links', to='companies.company', verbose_name='関連会社'),
        ),
        migrations.AddField(
            model_name='expense',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_links', to='customers.customer', verbose_name='関連顧客'),
        ),
        migrations.AddField(
            model_name='incomesource',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_links', to='cases.case', verbose_name='関連案件'),
        ),
        migrations.AddField(
            model_name='incomesource',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_links', to='companies.company', verbose_name='関連会社'),
        ),
        migrations.AddField(
            model_name='incomesource',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_links', to='customers.customer', verbose_name='関連顧客'),
        ),
    ]
