# Generated by Django 4.2.30 on 2026-09-28 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0016_income_expense_party_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='visareturnapplication',
            name='import_row_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='取込元の行番号'),
        ),
        migrations.CreateModel(
            name='VisaImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='ファイル名')),
                ('file_sha256', models.CharField(db_index=True, max_length=64, verbose_name='ファイルハッシュ')),
                ('sheet_name', models.CharField(blank=True, max_length=100, verbose_name='シート名')),
                ('encoding', models.CharField(blank=True, max_length=30, verbose_name='文字コード')),
                ('column_mapping', models.JSONField(blank=True, default=dict, verbose_name='列の対応付け')),
                ('mode', models.CharField(choices=[('valid_only', '有効な行だけ作成し、誤り行は報告'), ('all_or_nothing', 'すべて正しい場合だけ作成')], default='valid_only', max_length=20, verbose_name='作成方式')),
                ('status', models.CharField(choices=[('parsed', '読込済み'), ('partial', '一部作成'), ('completed', '作成完了')], default='parsed', max_length=20, verbose_name='状態')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='行数')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='作成件数')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='誤り件数')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='重複スキップ件数')),
                ('results', models.JSONField(blank=True, default=dict, verbose_name='行ごとの結果')),
                ('committed_request_ids', models.JSONField(blank=True, default=list, verbose_name='処理済み request_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visa_import_batches', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '返签visa表 一括取込',
                'verbose_name_plural': '返签visa表 一括取込',
                'db_table': 'accounting_visa_import_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='visareturnapplication',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='accounting.visaimportbatch', verbose_name='取込バッチ'),
        ),
    ]
