# Generated by Django 4.2.30 on 2026-10-02 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


# 初期規則（事務所共通の設定データ。支出記録などの業務データは書き換えない）。
# 提案先は 0002 で登録済みの既存カテゴリ「停车费」だけ。ここではカテゴリを作らない・有効化しない：
# - カテゴリが無い環境（名称変更・削除済み）では規則を作らずに終える。「駐車場代」等の重複主档も作らない。
# - カテゴリが無効化されている環境では規則だけ作る（無効なカテゴリは提案されない。有効化は管理者の判断）。
# どちらの場合も migrate は失敗させず、上線前検査 `check_expense_category_rules` が状態と対処を報告する。
# 照合キーは category_suggestions.normalize_key と同じ結果（NFKC・小文字・空白除去）を直接書く。
PARKING_CATEGORY = '停车费'
PARKING_RULES = (('駐車場', '駐車場'), ('停车场', '停车场'), ('parking', 'parking'))


def seed_parking_rules(apps, schema_editor):
    category_model = apps.get_model('accounting', 'ExpenseCategory')
    rule_model = apps.get_model('accounting', 'ExpenseCategorySuggestionRule')
    category = category_model.objects.filter(name=PARKING_CATEGORY).first()
    if category is None:
        return
    for pattern, key in PARKING_RULES:
        rule_model.objects.get_or_create(
            owner=None, match_field='place', pattern_key=key,
            defaults={'pattern': pattern, 'expense_category': category, 'priority': 0, 'is_active': True,
                      'source': 'seed'},
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0019_db_defaults_for_rollback_compat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategorySuggestionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=100, verbose_name='文字')),
                ('pattern_key', models.CharField(editable=False, max_length=100, verbose_name='照合キー')),
                ('match_field', models.CharField(choices=[('place', '場所'), ('expense_target', '費用対象'), ('note', '備考')], default='place', max_length=20, verbose_name='対象項目')),
                ('priority', models.IntegerField(default=0, verbose_name='優先度')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('source', models.CharField(choices=[('seed', '初期規則'), ('manual', '管理者が登録'), ('user_confirmed', '入力時に記憶')], default='manual', max_length=20, verbose_name='登録元')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_rules', to='accounting.expensecategory', verbose_name='提案するカテゴリ')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_category_rules', to=settings.AUTH_USER_MODEL, verbose_name='本人用の利用者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': '支出カテゴリの提案規則',
                'verbose_name_plural': '支出カテゴリの提案規則',
                'db_table': 'accounting_expense_category_rules',
                'ordering': ['-priority', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='expensecategorysuggestionrule',
            constraint=models.UniqueConstraint(fields=('owner', 'match_field', 'pattern_key'), name='uniq_expense_category_rule_pattern'),
        ),
        migrations.RunPython(seed_parking_rules, migrations.RunPython.noop),
    ]
