# Generated by Django 4.2.30 on 2026-10-03 13:41

import apps.accounting.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0020_expense_category_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='visareturnapplication',
            name='guarantor_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='accounting.visaguarantortemplate', verbose_name='使用した担保人テンプレート'),
        ),
        migrations.CreateModel(
            name='VoucherStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_kind', models.CharField(max_length=20, verbose_name='帳票種別')),
                ('voucher_number', models.CharField(blank=True, max_length=50, verbose_name='帳票番号')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='変更前の状態')),
                ('to_status', models.CharField(max_length=20, verbose_name='変更後の状態')),
                ('version', models.PositiveIntegerField(default=0, verbose_name='発行の版')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='変更時の帳票内容')),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='理由・メモ')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='変更日時')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_history', to='accounting.accountingvoucher', verbose_name='帳票')),
            ],
            options={
                'verbose_name': '請求書・領収書の状態履歴',
                'verbose_name_plural': '請求書・領収書の状態履歴',
                'db_table': 'accounting_voucher_status_history',
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VisaReturnPdfGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失敗')], max_length=10, verbose_name='結果')),
                ('method', models.CharField(blank=True, choices=[('form', 'フォーム項目へ入力'), ('coordinates', '座標へ描画')], max_length=20, verbose_name='生成方式')),
                ('template_name', models.CharField(blank=True, max_length=100, verbose_name='PDF テンプレート')),
                ('template_version', models.CharField(blank=True, max_length=64, verbose_name='PDF テンプレートの版')),
                ('guarantor_template_version', models.CharField(blank=True, max_length=40, verbose_name='担保人テンプレートの版')),
                ('file', models.FileField(blank=True, max_length=255, upload_to=apps.accounting.models.visa_pdf_upload_to, verbose_name='PDF')),
                ('file_sha256', models.CharField(blank=True, max_length=64, verbose_name='SHA-256')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='サイズ')),
                ('error_code', models.CharField(blank=True, max_length=40, verbose_name='エラー種別')),
                ('error_message', models.TextField(blank=True, verbose_name='エラー内容')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='詳細')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成日時')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_generations', to='accounting.visareturnapplication', verbose_name='申請')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='生成者')),
                ('guarantor_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.visaguarantortemplate', verbose_name='担保人テンプレート')),
            ],
            options={
                'verbose_name': '返签visa表 PDF 生成記録',
                'verbose_name_plural': '返签visa表 PDF 生成記録',
                'db_table': 'accounting_visa_return_pdf_generations',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
