# Generated by Django 4.2.30 on 2026-10-06 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0021_voucher_history_visa_generations'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingvoucher',
            name='internal_line_costs',
            field=models.JSONField(blank=True, default=list, verbose_name='明細の委託底価（社内）'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='internal_line_costs',
            field=models.JSONField(blank=True, default=list, verbose_name='明細の委託底価（社内）'),
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='分類')),
                ('name', models.CharField(max_length=255, verbose_name='項目名')),
                ('default_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='対客標準価格')),
                ('price_type', models.CharField(choices=[('tax_included', '税込'), ('tax_excluded', '税抜')], default='tax_included', max_length=20, verbose_name='価格の税区分')),
                ('floor_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='委託底価')),
                ('professional_type', models.CharField(blank=True, choices=[('', 'なし'), ('gyousei', '行政書士'), ('tax_accountant', '税理士'), ('judicial_scrivener', '司法書士'), ('labor_consultant', '社会保険労務士'), ('other', 'その他')], max_length=30, verbose_name='委託専門家')),
                ('tax_category', models.CharField(choices=[('tax_10', '10％'), ('tax_8', '8％'), ('non_taxable', '非課税')], default='tax_10', max_length=20, verbose_name='税区分')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='単位')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('note', models.TextField(blank=True, verbose_name='社内メモ')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='並び順')),
                ('first_used_at', models.DateTimeField(blank=True, null=True, verbose_name='初回使用日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'サービス項目',
                'verbose_name_plural': 'サービス項目',
                'db_table': 'accounting_service_items',
                'ordering': ['sort_order', 'id'],
                'permissions': [('use_service_item', 'サービス項目の閲覧・選択'), ('manage_service_item', 'サービス項目の登録・変更'), ('view_service_floor_price', '委託底価の閲覧・変更')],
            },
        ),
        migrations.CreateModel(
            name='IssuedLineCostSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_kind', models.CharField(max_length=20, verbose_name='帳票種別')),
                ('document_id', models.PositiveBigIntegerField(verbose_name='帳票 ID')),
                ('document_number', models.CharField(blank=True, max_length=50, verbose_name='帳票番号')),
                ('version', models.PositiveIntegerField(verbose_name='版')),
                ('line_costs', models.JSONField(blank=True, default=list, verbose_name='明細の委託底価')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='発行者')),
                ('status_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.voucherstatushistory', verbose_name='対応する状態履歴')),
            ],
            options={
                'verbose_name': '発行時の委託底価',
                'verbose_name_plural': '発行時の委託底価',
                'db_table': 'accounting_issued_line_cost_snapshots',
                'ordering': ['document_kind', 'document_id', 'version'],
            },
        ),
        migrations.AddConstraint(
            model_name='issuedlinecostsnapshot',
            constraint=models.UniqueConstraint(fields=('document_kind', 'document_id', 'version'), name='uniq_issued_line_cost_version'),
        ),
    ]
