# Generated by Django 4.2.30 on 2026-10-06 14:04

import apps.accounting.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0023_seifu_notice_fixed_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeifuNoticePdfGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', '成功')], default='success', max_length=10, verbose_name='結果')),
                ('request_id', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='操作 ID')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='宛名')),
                ('permit_number', models.CharField(max_length=30, verbose_name='許可番号')),
                ('notice_number', models.CharField(max_length=40, verbose_name='通知書番号')),
                ('issue_date', models.DateField(verbose_name='通知日')),
                ('template_key', models.CharField(max_length=60, verbose_name='テンプレート')),
                ('template_version', models.CharField(max_length=64, verbose_name='テンプレートの版')),
                ('font_version', models.CharField(max_length=64, verbose_name='字体の版')),
                ('method', models.CharField(max_length=30, verbose_name='生成方式')),
                ('file', models.FileField(max_length=255, upload_to=apps.accounting.models.seifu_pdf_upload_to, verbose_name='PDF')),
                ('file_sha256', models.CharField(max_length=64, verbose_name='SHA-256')),
                ('file_size', models.PositiveIntegerField(verbose_name='サイズ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='生成者')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='accounting.seifunoticepdfrecord', verbose_name='記録')),
            ],
            options={
                'verbose_name': '清風合格通知書 PDF 生成記録',
                'verbose_name_plural': '清風合格通知書 PDF 生成記録',
                'db_table': 'accounting_seifu_notice_pdf_generations',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
