# Generated by Django 4.2.30 on 2026-10-06 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0024_seifu_notice_pdf_generations'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='code',
            field=models.SlugField(blank=True, max_length=60, null=True, unique=True, verbose_name='コード'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='price_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='価格確定日時'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='price_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='価格確定者'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='price_status',
            field=models.CharField(choices=[('provisional', '暫定価格'), ('confirmed', '確定価格')], default='provisional', max_length=20, verbose_name='価格の状態'),
        ),
    ]
