# Generated by Django 4.2.30 on 2026-07-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={'ordering': ['-occurred_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='timeline',
            name='occurred_at',
            field=models.DateField(blank=True, null=True, verbose_name='発生日'),
        ),
    ]
