# Generated by Django 4.2.30 on 2026-09-06 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timelines', '0002_alter_timeline_options_timeline_occurred_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeline',
            name='event_type',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='timeline',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
