# Generated by Django 4.2.30 on 2026-09-27 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='protected_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '保護アカウント',
                'verbose_name_plural': '保護アカウント',
                'db_table': 'authentication_protected_accounts',
                'permissions': [('manage_users', 'アカウント管理'), ('use_diagnostics', '診断機能の利用')],
            },
        ),
    ]
