# Generated by Django 4.2.30 on 2026-07-13 06:00

from django.db import migrations, models
import django.db.models.deletion


def migrate_task_statuses(apps, schema_editor):
    task_model = apps.get_model('tasks', 'Task')
    task_model.objects.filter(status='todo').update(status='pending')
    task_model.objects.filter(status='done').update(status='completed')
    task_model.objects.filter(status='未対応').update(status='pending')
    task_model.objects.filter(status='対応中').update(status='in_progress')
    task_model.objects.filter(status='完了').update(status='completed')
    task_model.objects.filter(status='保留').update(status='paused')


def reverse_task_statuses(apps, schema_editor):
    task_model = apps.get_model('tasks', 'Task')
    task_model.objects.filter(status='pending').update(status='todo')
    task_model.objects.filter(status='completed').update(status='done')
    task_model.objects.filter(status='paused').update(status='todo')
    task_model.objects.filter(status='cancelled').update(status='todo')


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='responsible_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', '未開始'), ('in_progress', '進行中'), ('completed', '完了'), ('paused', '一時停止'), ('cancelled', '取消')], default='pending', max_length=20),
        ),
        migrations.RunPython(migrate_task_statuses, reverse_task_statuses),
    ]
