# Generated by Django 4.2.30 on 2026-10-05 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0021_db_defaults_for_rollback_compat'),
        ('employees', '0002_employee_user'),
        ('tasks', '0002_alter_task_options_task_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='報告日')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('confirmed', '確定')], default='draft', max_length=20, verbose_name='状態')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='生成時の計画項目')),
                ('generated_text', models.TextField(blank=True, verbose_name='生成文')),
                ('final_text', models.TextField(blank=True, verbose_name='報告本文')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='生成日時')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='確定日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '業務報告',
                'verbose_name_plural': '業務報告',
                'db_table': 'daily_work_reports',
                'ordering': ['-report_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='carried_from',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carried_to', to='tasks.task', verbose_name='結転元'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='登録者'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', '高'), ('normal', '中'), ('low', '低')], default='normal', max_length=10, verbose_name='優先度'),
        ),
        migrations.AddField(
            model_name='task',
            name='result_note',
            field=models.TextField(blank=True, default='', verbose_name='結果メモ'),
        ),
        migrations.AddField(
            model_name='task',
            name='work_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='作業日'),
        ),
        migrations.AlterField(
            model_name='task',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', '未開始'), ('in_progress', '進行中'), ('completed', '完了'), ('paused', '一時停止'), ('cancelled', '取消'), ('carried_over', '結転済み')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['responsible_employee', 'work_date'], name='task_plan_owner_date_idx'),
        ),
        migrations.AddField(
            model_name='dailyworkreport',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='確定者'),
        ),
        migrations.AddField(
            model_name='dailyworkreport',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports', to='employees.employee', verbose_name='担当者'),
        ),
        migrations.AddField(
            model_name='dailyworkreport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='生成者'),
        ),
        migrations.AddField(
            model_name='dailyworkreport',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最終編集者'),
        ),
        migrations.AddConstraint(
            model_name='dailyworkreport',
            constraint=models.UniqueConstraint(fields=('employee', 'report_date'), name='daily_report_one_per_employee_day'),
        ),
    ]
