# Generated by Django 4.2.30 on 2026-06-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='口座番号'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_account_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='預金種別'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100, verbose_name='支店名'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='銀行名'),
        ),
        migrations.AddField(
            model_name='company',
            name='corporate_registration_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='会社法人等番号'),
        ),
        migrations.AddField(
            model_name='company',
            name='fiscal_month',
            field=models.CharField(blank=True, max_length=2, verbose_name='決算月'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_kana',
            field=models.CharField(blank=True, max_length=150, verbose_name='会社名フリガナ'),
        ),
        migrations.AddField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='郵便番号'),
        ),
    ]
