# Generated by Django 4.2.30 on 2026-06-30 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_bank_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_kana', models.CharField(blank=True, max_length=100, verbose_name='フリガナ')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='役職')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('gender', models.CharField(blank=True, max_length=20, verbose_name='性別')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='国籍')),
                ('residence_status', models.CharField(blank=True, max_length=100, verbose_name='在留資格')),
                ('residence_card_no', models.CharField(blank=True, max_length=50, verbose_name='在留カード番号')),
                ('residence_expiry', models.DateField(blank=True, null=True, verbose_name='在留期限')),
                ('passport_no', models.CharField(blank=True, max_length=50, verbose_name='パスポート番号')),
                ('passport_expiry', models.DateField(blank=True, null=True, verbose_name='パスポート期限')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='メール')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='住所')),
                ('my_number', models.CharField(blank=True, max_length=30, verbose_name='マイナンバー')),
                ('employment_start_date', models.DateField(blank=True, null=True, verbose_name='入社日')),
                ('employment_end_date', models.DateField(blank=True, null=True, verbose_name='退社日')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='companies.company')),
            ],
            options={
                'db_table': 'company_staff',
                'ordering': ['company', 'name'],
            },
        ),
    ]
