# Generated by Django 4.2.30 on 2026-07-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companystaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='representative_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='代表者氏名'),
        ),
        migrations.AddField(
            model_name='company',
            name='representative_name_kana',
            field=models.CharField(blank=True, max_length=100, verbose_name='代表者フリガナ'),
        ),
    ]
