# Generated by Django 4.2.30 on 2026-07-01 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_my_number_customer_postal_code_and_more'),
        ('companies', '0004_company_representative_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='representative_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representative_companies', to='customers.customer', verbose_name='代表者顧客'),
        ),
    ]
