# Generated by Django 4.2.30 on 2026-08-03 07:38

import apps.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_representative_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companystaff',
            name='my_number',
            field=apps.common.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='マイナンバー'),
        ),
    ]
