# Generated by Django 4.2.30 on 2026-08-04 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_encrypt_my_number_data'),
        ('companies', '0007_encrypt_my_number_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystaff',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_staff_roles', to='customers.customer', verbose_name='顧客'),
        ),
    ]
