# Generated by Django 4.2.30 on 2026-08-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_companystaff_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='establishment_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='事業所番号'),
        ),
        migrations.AddField(
            model_name='company',
            name='establishment_symbol',
            field=models.CharField(blank=True, max_length=30, verbose_name='事業所整理記号'),
        ),
    ]
