# Generated by Django 4.2.30 on 2026-08-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_company_establishment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='representative_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='代表者住所'),
        ),
        migrations.AddField(
            model_name='company',
            name='representative_postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='代表者郵便番号'),
        ),
    ]
