# Generated by Django 4.2.30 on 2026-09-29 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='ファイル名')),
                ('file_sha256', models.CharField(db_index=True, max_length=64, verbose_name='SHA-256')),
                ('sheet', models.CharField(max_length=100, verbose_name='シート')),
                ('summary', models.JSONField(default=dict, verbose_name='集計')),
                ('report', models.JSONField(default=dict, verbose_name='報告（行ごとの元の値・規範化・誤り・候補）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'real_estate_import_runs',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
