# Generated by Django 4.2.30 on 2026-09-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_import_runs'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalledger',
            name='fiscal_year_end_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='事業年度末月（快照）'),
        ),
    ]
