# Generated by Django 4.2.30 on 2026-10-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0004_collaborative_ledger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realestatetransaction',
            options={'ordering': ['-created_at', '-id'], 'permissions': [('use_real_estate', '不動産モジュールを利用'), ('view_real_estate', '不動産記録を閲覧'), ('create_real_estate', '不動産記録を新規登録'), ('change_real_estate', '不動産記録を編集'), ('bulk_change_real_estate', '不動産記録を一括変更'), ('archive_real_estate', '不動産記録をアーカイブ'), ('restore_real_estate', '不動産記録を復元'), ('export_real_estate', '不動産記録・台帳を出力'), ('manage_legal_ledger', '不動産：法定台帳を管理'), ('correct_legal_ledger', '不動産：法定台帳を更正'), ('close_legal_ledger_year', '不動産：法定台帳の年度を締める'), ('manage_profit_distribution', '不動産：内部利益配分の閲覧・編集'), ('import_real_estate', '不動産：LIST 取込を実行')], 'verbose_name': '不動産取引', 'verbose_name_plural': '不動産取引'},
        ),
    ]
