# Generated by Django 4.2.30 on 2026-09-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'permissions': [('document_view_all', '担当外を含む全ファイルのメタデータ閲覧'), ('document_download_all', '担当外のファイルのダウンロード・プレビュー')]},
        ),
    ]
