# Generated by Django 4.2.30 on 2026-09-28 13:52

import apps.documents.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0003_alter_document_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='archive_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='アーカイブ理由'),
        ),
        migrations.AddField(
            model_name='document',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='アーカイブ日時'),
        ),
        migrations.AddField(
            model_name='document',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_documents', to=settings.AUTH_USER_MODEL, verbose_name='アーカイブ実行者'),
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('identity', '本人確認書類'), ('residence', '在留関係'), ('application', '申請書類'), ('certificate', '証明書'), ('company', '会社書類'), ('contract', '契約・請求'), ('correspondence', '連絡・通知'), ('other', 'その他')], default='other', max_length=30, verbose_name='分類'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='アーカイブ済み'),
        ),
        migrations.AddField(
            model_name='document',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='SHA-256'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='登録者'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=apps.documents.models.document_upload_to),
        ),
        migrations.CreateModel(
            name='DocumentReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_file', models.CharField(max_length=255, verbose_name='差し替え前の保存名')),
                ('previous_file_name', models.CharField(blank=True, max_length=255, verbose_name='差し替え前の元ファイル名')),
                ('previous_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='差し替え前のサイズ')),
                ('previous_sha256', models.CharField(blank=True, max_length=64, verbose_name='差し替え前の SHA-256')),
                ('previous_content_type', models.CharField(blank=True, max_length=100, verbose_name='差し替え前の MIME')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='理由')),
                ('replaced_at', models.DateTimeField(auto_now_add=True, verbose_name='差し替え日時')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacements', to='documents.document')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_replacements', to=settings.AUTH_USER_MODEL, verbose_name='差し替え実行者')),
            ],
            options={
                'db_table': 'case_document_replacements',
                'ordering': ['-replaced_at', '-id'],
            },
        ),
    ]
