# Generated by Django 4.2.30 on 2026-10-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_db_defaults_for_rollback_compat'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_label',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='資料内容'),
        ),
        migrations.AddField(
            model_name='document',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='表示ファイル名'),
        ),
    ]
