# Generated by Django 4.2.30 on 2026-06-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_gender_customer_name_kana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='residence_card_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='familymember',
            name='residence_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='residence_status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
