# Generated by Django 4.2.30 on 2026-06-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_familymember_residence_card_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='my_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='マイナンバー'),
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='郵便番号'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='my_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='マイナンバー'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='郵便番号'),
        ),
    ]
