# Generated by Django 4.2.30 on 2026-08-03 07:38

import apps.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_my_number_customer_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='my_number',
            field=apps.common.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='マイナンバー'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='my_number',
            field=apps.common.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='マイナンバー'),
        ),
    ]
