# Generated by Django 4.2.30 on 2026-08-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_encrypt_my_number_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidenceStatusMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, choices=[('work', '就労系'), ('non_work', '非就労系'), ('status', '身分・地位系'), ('specified', '特定活動')], max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'residence_status_masters',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
