# Generated by Django 4.2.30 on 2026-08-04 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_residencestatusmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='family_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='family_links', to='customers.customer', verbose_name='本人（顧客）'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
