# Generated by Django 4.2.30 on 2026-09-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_family_member_family_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'permissions': [('customer_view_all', '担当外を含む顧客・会社の詳細閲覧（機微項目を除く）'), ('view_sensitive_identity', '担当外の在留カード番号・旅券番号・口座情報の閲覧')]},
        ),
    ]
