# Generated by Django 4.2.30 on 2026-10-06 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_party_link_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'permissions': [('customer_view_all', '担当外を含む顧客・会社の詳細閲覧（機微項目を除く）'), ('view_sensitive_identity', '担当外の在留カード番号・旅券番号・口座情報の閲覧'), ('customer_link_all', '他担当の進行中案件がある顧客の関連付け（案件・受付・家族・職員・代表者）'), ('company_link_all', '他担当の進行中案件がある会社の関連付け（案件・受付）'), ('reveal_my_number', 'マイナンバーの表示（見られる顧客・家族に限る）')]},
        ),
    ]
